#!/bin/bash -l
#PBS -l walltime=0:05:00
#PBS -A rainfall
#PBS -r y
source /home/rjackson/.bashrc
cd /lcrc/group/earthscience/rjackson/wfip3/scripts
mamba activate wfip3_env
YESTERDAY=20240$PBS_ARRAY_INDEX
python concatenate_sonic_files.py z01 $YESTERDAY
