#!/bin/bash -l
#PBS -l walltime=6:00:00
#PBS -A rainfall
#PBS -r y
source /home/rjackson/.bashrc
cd /lcrc/group/earthscience/rjackson/wfip3/scripts
mamba activate pydsd_env
YESTERDAY=20231$PBS_ARRAY_INDEX
python parsivel_ingest.py $YESTERDAY
