#!/bin/bash -l
#PBS -l walltime=2:00:00
#PBS -A rainfall
#PBS -r y
source /home/rjackson/.bashrc
cd /lcrc/group/earthscience/rjackson/wfip3/scripts
mamba activate wfip3_env
printf -v j "%04d" $PBS_ARRAY_INDEX
YESTERDAY=2024$j
#python download_data.py $YESTERDAY
#python dl-ingest.py --date=$YESTERDAY
python process_vad.py $YESTERDAY

